version: '3.7'

services:

  police-app:
    container_name: police-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=eu-west-2
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8001:8080'
