name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build container
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: docker-compose up -d

    - name: Lint check
      run: docker-compose exec -T police-app sh -c "npm run lint"  

    - name: Build app
      run: docker-compose exec -T police-app sh -c "npm run build"

    - name: Deploy app
      run: docker-compose exec -T police-app sh -c "npm run deploy"

